version: '3.1'

services:
    mysql_db:
        image: mysql:latest
        cap_add:
            - SYS_NICE # CAP_SYS_NICE mbind: operation not permitted fix
        # use this command for mysql 8 or greater. It changed auth sheme
        command: '--default-authentication-plugin=mysql_native_password'
        restart: always
        ports:
            - 63306:3306
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./docker-store/mysql:/var/lib/mysql
        networks:
            - local-issue-tracker-dev

networks:
    local-issue-tracker-dev:
        ipam:
            config:
                - subnet: 172.51.0.0/24
